config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :orders, only: [:create, :new, :index]
  get "/status", to: "orders#status"
  get "/track/:id", to: "orders#track_order"
  get "/edit_status/:id", to: "orders#edit_status", as: "edit_status"
  post "/order", to: "orders#change_status"
  get "/search", to: "orders#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors.add attribute, (options[:message] || "is not an email")
    end
  end
end


class Order < ApplicationRecord
  validates :sender_full_name, presence: true
  validates :sender_address, presence: true
  validates :sender_email, presence: true, email: true
  validates :sender_phone_no, length: { is: 10}
  validates :sender_pin_code, length: { is: 6}
  validates :receiver_full_name, presence: true
  validates :receiver_address, presence: true
  validates :receiver_email, presence: true, email: true
  validates :receiver_phone_no, length: { is: 10}
  validates :receiver_pin_code, length: { is: 6}
  validates :weight, numericality: true
  validates :type_of_service, :inclusion=> { :in => ['Regular', 'Speed Post'] }
  validates :cost_of_service, numericality: true
  validates :payment, :inclusion=> { :in => ['COD', 'Prepaid'] }
  validates :status, :inclusion=> { :in => ['Sent', 'In Transit', 'Delivered'] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @order = Order.new(order_params)
    if @order.save
      EmailJob.perform_later @order
      redirect_to :new_order, notice: 'Order Created Successfully'
    else
      flash.now[:alert] = @order.errors.full_messages
      render :new
    end
  end

  def index
    @orders = Order.all
  end

  def edit_status
    @order = Order.find(params[:id])
  end

  def change_status
    @order = Order.find(params[:id])
    @order.status = params[:status]
    if @order.save
      redirect_to :orders
    else
      render :edit_status
    end
  end

  def track_order
    @order = Order.find(params[:id])
  end

  def status
    @status = Order.find(params[:id]).status
  end

  def search
  end

   def new
     @order = Order.new
   end

  private

  def order_params
    params.require(:order).permit(:sender_full_name, :sender_address, :sender_email, :sender_phone_no, :sender_pin_code, :receiver_full_name, :receiver_address, :receiver_email, :receiver_phone_no, :receiver_pin_code, :weight, :type_of_service, :payment).merge(:cost_of_service => cost, :status => 'Sent')
  end

  def cost
    return params[:order][:weight].to_f * 10 if params[:order][:type_of_service] == 'Regular'
    params[:order][:weight].to_f * 20
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/edit_status.html.erb
<nav class="navbar navbar-dark bg-primary">
  <span class="navbar-brand mb-0 h1">Edit Status</span>
</nav>
<h6> The current status of courier is <%= @order.status %>. To change the status provide it in the below box</h6>
<%= form_with local: true, url: "/order/", method: :post do |form| %>
  <div>
    <%= form.hidden_field :id, value: @order.id %>
  </div>

  <div>
    <%= form.text_field :status, size: 100 %>
  </div>

  <div>
    <%= form.submit "Update"%>
  </div>
<% end %> 

app/views/orders/index.html.erb
<nav class="navbar navbar-dark bg-primary">
  <span class="navbar-brand mb-0 h1">Orders</span>
</nav>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Sender Name</th>
      <th scope="col">Receiver Name</th>
      <th scope="col">Present Status</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr scope="row">
        <td><%= order.sender_full_name %></td>
        <td><%= order.receiver_full_name %></td>
        <td><%= link_to order.status, edit_status_path(order.id) %></td>
      </tr>
  </tbody>
  <% end %>

app/views/orders/new.html.erb
<nav class="navbar navbar-dark bg-primary">
  <span class="navbar-brand mb-0 h1">New Order</span>
</nav>
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<%= form_with local: true, model: @order do |form| %>
 <div class="container">
  <div class="row align-items-start">
    <div class="col">
      <div>
        <%= form.label :sender_full_name %><br>
        <%= form.text_field :sender_full_name %>
      </div>

      <div>
        <%= form.label :sender_address %><br>
        <%= form.text_area :sender_address %>
      </div>

      <div>
        <%= form.label :sender_email %><br>
        <%= form.text_field :sender_email %>
      </div>

      <div>
        <%= form.label :sender_phone_no %><br>
        <%= form.text_field :sender_phone_no %>
      </div>

      <div>
        <%= form.label :sender_pin_code %><br>
        <%= form.text_field :sender_pin_code %>
      </div>
    </div>

    <div class="col">
      <div>
        <%= form.label :receiver_full_name %><br>
        <%= form.text_field :receiver_full_name %>
      </div>

      <div>
        <%= form.label :receiver_address %><br>
        <%= form.text_area :receiver_address %>
      </div>

      <div>
        <%= form.label :receiver_email %><br>
        <%= form.text_field :receiver_email %>
      </div>

      <div>
        <%= form.label :receiver_phone_no %><br>
        <%= form.text_field :receiver_phone_no %>
      </div>
  
      <div>
        <%= form.label :receiver_pin_code %><br>
        <%= form.text_field :receiver_pin_code %>
      </div>
    </div>

    <div class="col">
      <div>
        <%= form.label :weight %><br>
        <%= form.number_field :weight, step: 0.01 %>
      </div>

      <div>
        <%= form.label :type_of_service %><br>
        <%= form.select :type_of_service, ['Regular', 'Speed Post']%>
      </div>

      <div>
        <%= form.label :payment %><br>
        <%= form.select :payment, ['COD', 'Prepaid']%>
      </div>
    </div>
  </div>
</div>
  
  <div class="d-flex justify-content-center">
    <%= form.submit %>
  </div>
<% end %> 

app/views/orders/search.html.erb
<nav class="navbar navbar-dark bg-primary">
  <span class="navbar-brand mb-0 h1">Search</span>
</nav>
<%= form_with local: true, url: "/status", method: :get do |form| %>
  <div>
    <%= form.text_field :id, placeholder: "Enter the unique id to search the order", size: 100 %>
    <%= form.submit "Search"%>
  </div>
<% end %> 

app/views/orders/status.html.erb
<nav class="navbar navbar-dark bg-primary">
  <span class="navbar-brand mb-0 h1">Courier Status</span>
</nav>
<h6>
  <% if @status == 'In Transit' %>
    Your courier is 
  <% else %>
    Your courier has been
  <% end %>
  <%= @status %>
</h6>
  

app/views/orders/track_order.html.erb
<nav class="navbar navbar-dark bg-primary">
  <span class="navbar-brand mb-0 h1">Track Orders</span>
</nav>
  <div  class="d-flex justify-content-center">
    <h4 class="text-info">
      <small  class="text-body">
        <% if @order.status == 'In Transit' %>
          Your courier is 
        <% else %>
          Your courier has been
        <% end %>
      </small>
      <%= @order.status %>
    </h4>
  </div>
  <div class="container">
    <div class="row align-items-start">
      <div class="col">
        <div>
          <%= label_tag "weight:" %>
          <%= @order.weight %>
        </div>

        <div>
          <%= label_tag "cost_of_service:" %>
          <%= @order.cost_of_service %>
        </div>
      </div>

      <div class="col">
        <div>
          <%= label_tag "type_of_service:" %>
          <%= @order.type_of_service%>
        </div>

        <div>
          <%= label_tag "payment:" %>
          <%= @order.payment%>
        </div>
      </div>
    </div>

    <div class="row align-items-center">
      <div class="col">
        <div>
          <%= label_tag "sender_full_name:" %>
          <%= @order.sender_full_name %>
        </div>

        <div>
          <%= label_tag "sender_address:" %>
          <%= @order.sender_address %>
        </div>

        <div>
          <%= label_tag "sender_email:" %>
          <%= @order.sender_email %>
        </div>

        <div>
          <%= label_tag "sender_phone_no:" %>
          <%= @order.sender_phone_no %>
        </div>

        <div>
          <%= label_tag "sender_pin_code:" %>
          <%= @order.sender_pin_code %>
        </div>
      </div>

      <div class="col">
        <div>
          <%= label_tag "receiver_full_name:" %>
          <%= @order.receiver_full_name %>
        </div>

        <div>
          <%= label_tag   "receiver_address:" %>
          <%= @order.receiver_address %>
        </div>

        <div>
          <%= label_tag "receiver_email:" %>
          <%= @order.receiver_email %>
        </div>

        <div>
          <%= label_tag "receiver_phone_no:" %>
          <%= @order.receiver_phone_no %>
        </div>

        <div>
          <%= label_tag "receiver_pin_code:" %>
          <%= @order.receiver_pin_code %>
        </div>
      </div>
    </div>
  </div>